apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: us.gcr.io/taeho-io-220708/auth:${CIRCLE_SHA1}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 81
          env:
            - name: AUTH_SIGNING_METHOD
              valueFrom:
                secretKeyRef:
                  name: taeho-envs
                  key: AUTH_SIGNING_METHOD
            - name: AUTH_SIGNING_PEM
              valueFrom:
                secretKeyRef:
                  name: taeho-envs
                  key: AUTH_SIGNING_PEM
            - name: AUTH_VERIFYING_PEM
              valueFrom:
                secretKeyRef:
                  name: taeho-envs
                  key: AUTH_VERIFYING_PEM
            - name: AUTH_TOKEN_ISSUER
              valueFrom:
                secretKeyRef:
                  name: taeho-envs
                  key: AUTH_TOKEN_ISSUER
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:80"]
            initialDelaySeconds: 3
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:80"]
            initialDelaySeconds: 5

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: auth-hpa
  labels:
    app: auth
spec:
  scaleTargetRef:
    kind: Deployment
    name: auth
    apiVersion: apps/v1beta1
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

---

apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    app: auth
spec:
  ports:
    - port: 80
      name: grpc
    - port: 81
      name: http
  selector:
    app: auth

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: auth-route-public-no-auth
spec:
  hosts:
    - auth.taeho.io
  gateways:
    - public-gateway
  http:
    - match:
        - uri:
            prefix: /jwks
      route:
        - destination:
            host: auth
            port:
              number: 81
